name: Generate Snake

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            --color_snake "#FFFFFF"
            --color_dots "#FF0000,#FFA500,#FFFF00,#00FF00,#0000FF,#4B0082,#EE82EE"
            --background_color "#00000000"

      - name: Commit and push the snake svg
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate contribution graph"
          add: "dist/github-contribution-grid-snake.svg"
