name: Generate Snake

on:
  schedule:
    - cron: "* 0/1 * * *" # executa todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: '#FF0000' # vermelho puro
          color_dots: '#EEEEEE,#CCCCCC,#999999,#666666,#333333' # escala de cinza
          background_color: '#00000000' # fundo transparente
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
