name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Set permissions for dist directory
        run: sudo chmod -R 777 dist

      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Apply unique color changing effect
        run: |
          # Define a set of unique colors for the animation (using a simple set of colors instead of gradient)
          COLORS='
          <style>
            @keyframes colorChange {
              0% { fill: #FF0000; }   /* Red */
              25% { fill: #00FF00; }  /* Green */
              50% { fill: #0000FF; }  /* Blue */
              75% { fill: #FFFF00; }  /* Yellow */
              100% { fill: #8B00FF; } /* Purple */
            }

            .s {
              animation: colorChange 5s infinite; /* 5 seconds for one cycle */
            }
          </style>'

          # Insere o estilo de animação no SVG antes da tag de fechamento </svg>
          sed -i "s|</svg>|$COLORS</svg>|" dist/github-contribution-grid-snake.svg

          # Aplica a animação de cores a todos os elementos que têm a classe .s
          sed -i 's|\.s {fill:[^;]*;|\.s {fill:#FF0000; animation: colorChange 5s infinite;|g' dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate snake animation with unique color changing effect"
          git push origin HEAD:output --force
