name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Set permissions for dist directory
        run: sudo chmod -R 777 dist

      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Apply rainbow gradient using sed
        run: |
          # Define o gradiente rainbow
          RAINBOW='<defs><linearGradient id="rainbow" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stop-color="#FF0000"/><stop offset="20%" stop-color="#FF7F00"/><stop offset="40%" stop-color="#FFFF00"/><stop offset="60%" stop-color="#00FF00"/><stop offset="80%" stop-color="#0000FF"/><stop offset="100%" stop-color="#8B00FF"/></linearGradient></defs>'

          # Insere o <defs> após a tag <svg ...>
          sed -i "s|<svg[^>]*>|&$RAINBOW|" dist/github-contribution-grid-snake.svg

          # Substitui a linha da classe .s para usar o gradiente
          sed -i 's/\.s{[^}]*fill:[^;]*;/\.s{fill:url(#rainbow);/' dist/github-contribution-grid-snake.svg

          # Substitui todos os elementos de cor de preenchimento para o gradiente rainbow
          xmlstarlet ed -u '//svg//path/@fill' -v 'url(#rainbow)' dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg
          xmlstarlet ed -u '//svg//circle/@fill' -v 'url(#rainbow)' dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

          # Aplica o gradiente rainbow a todos os atributos "fill" do SVG
          xmlstarlet ed -u '//*[@fill]//@fill' -v 'url(#rainbow)' dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate snake animation with rainbow effect"
          git push origin HEAD:output --force
