name: Generate Snake Reworked

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set write permission for dist
        run: sudo chmod -R 777 dist

      - name: Inject animated rainbow style into SVG
        run: |
          echo '<style>
          @keyframes rainbow {
            0% { fill: #FF0000; }
            20% { fill: #FF7F00; }
            40% { fill: #FFFF00; }
            60% { fill: #00FF00; }
            80% { fill: #0000FF; }
            100% { fill: #8B00FF; }
          }
          .s {
            animation: rainbow 5s infinite;
          }
          </style>' > rainbow-style.txt

          FILE="dist/github-contribution-grid-snake.svg"

          # Modifica o arquivo SVG para incluir o <style> após a primeira tag <svg ...>
          sed -i '1s|<svg|<svg xmlns="http://www.w3.org/2000/svg">|' "$FILE"
          sed -i '/<svg[^>]*>/r rainbow-style.txt' "$FILE"

      - name: Commit and Push result
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate rainbow snake animation"
          git push origin HEAD:output --force
