name: Generate Snake Reworked

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set write permission for dist
        run: sudo chmod -R 777 dist

      - name: Inject animated rainbow style into SVG
        run: |
          # Criar o conteúdo CSS para animação dentro de <style>
          echo '<defs>
            <style type="text/css">
              @keyframes rainbow {
                0% { fill: #FF0000; }
                20% { fill: #FF7F00; }
                40% { fill: #FFFF00; }
                60% { fill: #00FF00; }
                80% { fill: #0000FF; }
                100% { fill: #8B00FF; }
              }
              .s {
                animation: rainbow 5s infinite;
              }
            </style>
          </defs>' > rainbow-style.txt

          # Definir o caminho do arquivo SVG
          FILE="dist/github-contribution-grid-snake.svg"

          # Inserir o CSS dentro de <defs> no início do arquivo SVG
          head -n 1 "$FILE" > tmp.svg
          cat rainbow-style.txt >> tmp.svg
          tail -n +2 "$FILE" >> tmp.svg

          # Substituir o arquivo original pelo arquivo modificado
          mv tmp.svg "$FILE"

      - name: Commit and Push result
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate rainbow snake animation"
          git push origin HEAD:output --force
