name: Generate Snake Reworked

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify SVG file exists and is not empty
        run: |
          FILE="dist/github-contribution-grid-snake.svg"
          if [ ! -f "$FILE" ]; then
            echo "Error: SVG file was not generated."
            exit 1
          fi
          if [ ! -s "$FILE" ]; then
            echo "Error: SVG file is empty."
            exit 1
          fi

      - name: Backup original SVG (with fixed permissions)
        run: |
          sudo chmod -R 777 dist
          cp dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-original.svg

      - name: Debug - Output original SVG content
        run: |
          echo "Original SVG content:"
          cat dist/github-contribution-grid-snake-original.svg

      - name: Inject animated rainbow style into SVG
        run: |
          FILE="dist/github-contribution-grid-snake.svg"
          BACKUP_FILE="dist/github-contribution-grid-snake-original.svg"

          # Verifica se o arquivo existe antes de prosseguir
          if [ ! -f "$FILE" ]; then
            echo "Error: SVG file not found. Aborting modification."
            exit 1
          fi

          # Adicionar o estilo diretamente dentro da tag <svg> na linha seguinte
          awk '/<svg/{print; print "<style>\n@keyframes rainbow {\n  0% { fill: #FF0000; }\n  20% { fill: #FF7F00; }\n  40% { fill: #FFFF00; }\n  60% { fill: #00FF00; }\n  80% { fill: #0000FF; }\n  100% { fill: #8B00FF; }\n}\n.rainbow {\n  animation: rainbow 5s infinite;\n}\n</style>"; next}1' "$FILE" > tmp.svg

          # Substituir o arquivo original pelo arquivo modificado
          mv tmp.svg "$FILE"

      - name: Debug - Output modified SVG content
        run: |
          echo "Modified SVG content:"
          cat dist/github-contribution-grid-snake.svg

      - name: Verify modified SVG
        run: |
          FILE="dist/github-contribution-grid-snake.svg"
          if [ ! -f "$FILE" ]; then
            echo "Error: Modified SVG file was not found."
            exit 1
          fi
          if [ ! -s "$FILE" ]; then
            echo "Error: Modified SVG file is empty."
            exit 1
          fi

          # Validar o arquivo SVG para garantir que não haja conteúdo extra
          if ! xmllint --noout "$FILE"; then
            echo "Error: SVG file is not well-formed."
            exit 1
          fi

      - name: Commit and Push result
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate rainbow snake animation"
          git push origin HEAD:output --force
