name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Set permissions for dist directory
        run: sudo chmod -R 777 dist

      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Apply rainbow gradient
        run: |
          # Adiciona <defs> e gradiente arco-íris
          xmlstarlet ed \
            -s "/svg" -t elem -n "defs" -v "" \
            -s "//defs" -t elem -n "linearGradient" -v "" \
            -i "//linearGradient" -t attr -n "id" -v "rainbow" \
            -i "//linearGradient" -t attr -n "x1" -v "0%" \
            -i "//linearGradient" -t attr -n "y1" -v "0%" \
            -i "//linearGradient" -t attr -n "x2" -v "100%" \
            -i "//linearGradient" -t attr -n "y2" -v "0%" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//linearGradient/stop[1]" -t attr -n "offset" -v "0%" \
            -i "//linearGradient/stop[1]" -t attr -n "stop-color" -v "#FF0000" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//linearGradient/stop[2]" -t attr -n "offset" -v "100%" \
            -i "//linearGradient/stop[2]" -t attr -n "stop-color" -v "#0000FF" \
            -u "//path/@fill" -v "url(#rainbow)" \
            dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

          # Substitui todos os elementos de cor de preenchimento para o gradiente rainbow
          xmlstarlet ed -u '//svg//path/@fill' -v 'url(#rainbow)' dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg
          xmlstarlet ed -u '//svg//circle/@fill' -v 'url(#rainbow)' dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

          # Aplica o gradiente rainbow a todos os atributos "fill" do SVG
          xmlstarlet ed -u '//*[@fill]//@fill' -v 'url(#rainbow)' dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate snake animation with rainbow effect"
          git push origin HEAD:output --force
