name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#f47fff&background_color=#00FF00
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure dist directory exists
        run: |
          mkdir -p dist

      - name: Set permissions for dist directory
        run: |
          sudo chmod -R 777 dist

      - name: Add rainbow gradient to snake
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

          # Adiciona o elemento <defs> ao SVG
          xmlstarlet ed -s "/svg" -t elem -n "defs" -v "" dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

          # Adiciona o gradiente arco-íris dentro de <defs>
          xmlstarlet ed \
            -s "//defs" -t elem -n "linearGradient" -v "" \
            -i "//linearGradient" -t attr -n "id" -v "rainbow" \
            -i "//linearGradient" -t attr -n "x1" -v "0%" \
            -i "//linearGradient" -t attr -n "y1" -v "0%" \
            -i "//linearGradient" -t attr -n "x2" -v "100%" \
            -i "//linearGradient" -t attr -n "y2" -v "0%" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//stop[1]" -t attr -n "offset" -v "0%" \
            -i "//stop[1]" -t attr -n "stop-color" -v "#FF0000" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//stop[2]" -t attr -n "offset" -v "14%" \
            -i "//stop[2]" -t attr -n "stop-color" -v "#FFA500" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//stop[3]" -t attr -n "offset" -v "28%" \
            -i "//stop[3]" -t attr -n "stop-color" -v "#FFFF00" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//stop[4]" -t attr -n "offset" -v "42%" \
            -i "//stop[4]" -t attr -n "stop-color" -v "#00FF00" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//stop[5]" -t attr -n "offset" -v "57%" \
            -i "//stop[5]" -t attr -n "stop-color" -v "#0000FF" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//stop[6]" -t attr -n "offset" -v "71%" \
            -i "//stop[6]" -t attr -n "stop-color" -v "#4B0082" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//stop[7]" -t attr -n "offset" -v "85%" \
            -i "//stop[7]" -t attr -n "stop-color" -v "#EE82EE" \
            -s "//linearGradient" -t elem -n "stop" -v "" \
            -i "//stop[8]" -t attr -n "offset" -v "100%" \
            -i "//stop[8]" -t attr -n "stop-color" -v "#FF0000" \
            dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

          # Aplica o gradiente nos caminhos da cobra pela cor antiga (#f47fff)
          xmlstarlet ed -u '//path[@fill="#f47fff"]/@fill' -v 'url(#rainbow)' dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate snake animation with rainbow effect"
          git push origin HEAD:output --force
