name: Generate Snake Rework

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Set permissions for dist directory
        run: sudo chmod -R 777 dist

      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Add animated rainbow style
        run: |
          # Criar o bloco <defs> com animação e salvá-lo em um arquivo
          cat <<EOF > defs.xml
<defs>
  <style>
    @keyframes rainbow {
      0%   { fill: #FF0000; }
      20%  { fill: #FF7F00; }
      40%  { fill: #FFFF00; }
      60%  { fill: #00FF00; }
      80%  { fill: #0000FF; }
      100% { fill: #8B00FF; }
    }
    .s {
      animation: rainbow 5s infinite;
    }
  </style>
</defs>
EOF

          # Inserir o conteúdo do defs.xml como primeiro filho da tag <svg>
          xmlstarlet ed -L -s "/svg" -t elem -n "tmpDefs" -v "" dist/github-contribution-grid-snake.svg
          xmlstarlet ed -L -u "//tmpDefs" -x "document('defs.xml')/defs" dist/github-contribution-grid-snake.svg
          xmlstarlet ed -L -r "//tmpDefs" -v "defs" dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate snake animation with animated rainbow effect"
          git push origin HEAD:output --force
