name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Set permissions for dist directory
        run: sudo chmod -R 777 dist

      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Apply color changing animation
        run: |
          # Criar o conteúdo de animação como um arquivo temporário
          echo '
          <defs>
            <style>
              @keyframes colorChange {
                0% { fill: #FF0000; }   /* Red */
                25% { fill: #FF7F00; }  /* Orange */
                50% { fill: #FFFF00; }  /* Yellow */
                75% { fill: #00FF00; }  /* Green */
                100% { fill: #0000FF; } /* Blue */
              }

              .s {
                animation: colorChange 5s infinite; /* Animação de 5 segundos por ciclo */
              }
            </style>
          </defs>
          ' > temp_styles.svg

          # Adicionar o conteúdo de animação antes do fechamento da tag </svg>
          # Isso vai garantir que o conteúdo seja inserido dentro do SVG e não após o fechamento.
          sed -i '/<\/svg>/i \\
          '"$(cat temp_styles.svg)" dist/github-contribution-grid-snake.svg

          # Aplica a animação a todos os elementos que têm a classe .s
          xmlstarlet ed -u '//svg//*[contains(@class, "s")]' -v 'style="animation: colorChange 5s infinite;"' dist/github-contribution-grid-snake.svg > tmp.svg && mv tmp.svg dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Generate snake animation with unique color changing effect"
          git push origin HEAD:output --force
