name: Generate Snake Profile

on:
  workflow_dispatch:

concurrency:
  group: "snake-workflow"  # Nome único para identificar o workflow
  cancel-in-progress: true  # Cancelar execuções anteriores

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: solundev
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: rainbow  # Definindo rainbow como cor
          color_snake_gradient: 1
          color_dots: '#EEEEEE,#CCCCCC,#999999,#666666,#333333'
          background_color: '#00000000'
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
